name: gzmn-worlds
version: '${version}'
main: nl.gzmn.playerworlds.backend.GzmnWorldsPlugin
api-version: '${apiVersion}'
description: Private per-player worlds for the GZMN network
authors: [GZMN]
website: https://github.com/LaurensBartelds/DynamicPlayerWorlds
folia-supported: false
